--- 
abstract: "An interface to Dot TK's Reseller API Program "
author: 
  - Dot TK Limited <dottk@cpan.org>
license: ~
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Domain-Register-TK
requires:
  LWP::UserAgent: 0
  XML::Simple: 0
  HTTP::Request: 0
  Crypt::SSLeay: 0
build_requires:
  Test::More: 0
provides: 
  Domain::Register::TK: 
    file: lib/Domain/Register/TK.pm
    version: 2.1
resources: 
  CPANForum: http://www.cpanforum.com/dist/Domain-Register-TK
  CPANTesters: http://cpantesters.perl.org/show/Domain-Register-TK.html#Domain-Register-TK-2.1
  CPANTools: http://search.cpan.org/tools/Domain-Register-TK-2.1
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Domain-Register-TK
version: 2.1
